### ISSUE TITLE
Ntkhang why you bann me😭😭im hardworking add 500 cmds im only try modified the goat.js with autoencrypted account.txt

### ISSUE THREAD

**Issue by Cliffvincent** [ntkhang03/Goat-Bot-V2#28]
I changed it because many accounts have been hacked because the cookie in the account.txt is not encrypted

**Comment by Cliffvincent** [comment]
![1000002474](https://github.com/ntkhang03/Goat-Bot-V2/assets/143686507/1f6437bb-6402-4d9b-bfef-f2abb324c960)

**Comment by ntkhang03** [comment]
it's an error from replit, there's no message saying you're banned 😐

**Comment by Cliffvincent** [comment]
Thank you for responding ♥️♥️

**Comment by ntkhang03** [comment]
> Thank you for responding im fixed♥️♥️
> 
> I hope to put an autoencrypted account.txt and there are as many hackers using the cookie

Just use private hosting, don't reveal your project to others. Don't make things difficult for yourself and others
