### ISSUE TITLE
Cannot convert undefined or nulll to object

### ISSUE THREAD

**Issue by WutzCyrus** [ntkhang03/Goat-Bot-V2#6]
I tred to install the required modules and non of them success it was all same error "_**npm ERR! Cannot convert undefined or null to object**_"

**Comment by WutzCyrus** [comment]
Nvm i fixed it

**Comment by ntkhang03** [comment]
You should tell the solution to other people having the same problem.
In this case, just update to the latest version

**Comment by WutzCyrus** [comment]
Right, i saw the repl suggestion when i tried to install module it says something like "should run in shell" so i tired it and it solved the problem
